# Generated by Django 4.2.2 on 2023-07-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_category_alter_features_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
