# Generated by Django 4.2.2 on 2023-07-09 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0006_alter_category_created_at_alter_category_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contributors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
