# Generated by Django 4.2.2 on 2023-07-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinformation',
            old_name='is_list_exists',
            new_name='is_lift_exists',
        ),
    ]
