# Generated by Django 3.2.5 on 2021-09-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Class',
        ),
        migrations.DeleteModel(
            name='FeaturesForProduct',
        ),
    ]
