# Generated by Django 3.2.5 on 2021-07-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagonalWheel_gyroscooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Features_gyroscooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='main_categories',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_categories',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product_gyroscooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagonal_wheel', to='catalogs.diagonalwheel_gyroscooter')),
                ('features', models.ManyToManyField(to='catalogs.Features_gyroscooter')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='catalogs.sub_categories')),
            ],
        ),
    ]
