# Generated by Django 3.2.5 on 2021-10-06 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20211006_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 19, 13, 12, 527707)),
        ),
    ]
