# Generated by Django 3.2.5 on 2021-07-15 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20210715_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_gyroscooter',
            name='diagonal_wheel',
        ),
        migrations.RemoveField(
            model_name='product_gyroscooter',
            name='features',
        ),
        migrations.AddField(
            model_name='main_categories',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.main_categories'),
        ),
        migrations.DeleteModel(
            name='DiagonalWheel_gyroscooter',
        ),
        migrations.DeleteModel(
            name='Features_gyroscooter',
        ),
    ]
