# Generated by Django 3.2.5 on 2021-07-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_auto_20210715_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_categories',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='Product_gyroscooter',
        ),
        migrations.DeleteModel(
            name='Sub_Categories',
        ),
    ]
