# Generated by Django 3.2.5 on 2021-07-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_auto_20210716_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Catalog_Features', to='catalogs.main_categories'),
            preserve_default=False,
        ),
    ]
