# Generated by Django 3.2.5 on 2021-08-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_auto_20210808_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='value',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
