# Generated by Django 3.2.5 on 2021-08-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_features_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
