# Generated by Django 3.2.5 on 2021-08-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_alter_features_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.CreateModel(
            name='Features_for_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featuress', to='catalogs.features')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogs.product')),
            ],
        ),
    ]
