# Generated by Django 4.2.2 on 2023-07-16 14:23

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.CharField()),
                ('picture', models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='private-bucket'), upload_to='')),
                ('url_to', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('read_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(to='products.cartitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(to='products.favouriteitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='private-bucket'), upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(to='authorization.notifications'),
        ),
    ]
