# Generated by Django 4.2.2 on 2023-07-29 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(storage=django_minio_backend.models.MinioBackend(bucket_name='private-bucket'), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('contributors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
