# Generated by Django 4.2.2 on 2023-07-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('features', models.JSONField(default=dict, verbose_name='Features_Product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Category', to='catalogs.category')),
            ],
        ),
    ]
