# Generated by Django 4.2.2 on 2023-07-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Class',
        ),
        migrations.AddField(
            model_name='features',
            name='slug',
            field=models.SlugField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(default=dict, verbose_name='Features_Product'),
        ),
        migrations.DeleteModel(
            name='FeaturesForProduct',
        ),
    ]
