# Generated by Django 4.2.2 on 2023-07-09 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('verified', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('logo', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField()),
                ('contributors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Features',
        ),
    ]
