# Generated by Django 4.2.2 on 2023-07-09 21:30

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_alter_organization_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='private-bucket'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
