# Generated by Django 4.2.2 on 2023-07-16 14:23

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_alter_organization_name_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(default=None, blank=True, null=True,storage=django_minio_backend.models.MinioBackend(bucket_name='private-bucket'), upload_to=''),
            preserve_default=False,
        ),
    ]
