  on:
    push:
      branches:
        - dev

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            ref: dev

        - name: SSH-KEY
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            name: id_rsa
            known_hosts: unnecessary

        - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

        - name: Deploy with rsync
          run: rsync -avz . -e "ssh -i $HOME/.ssh/id_rsa" root@${{ secrets.SSH_HOST }}:/home/digitalvixen

        - name: Run script
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd /home/digitalvixen/
              docker-compose restart
