  on:
    push:
      branches:
        - dev

  jobs:
    test:
      runs-on: ubuntu-latest
      name: run_django_tests
      steps:
        - uses: actions/checkout@v3
          with:
            ref: dev

        - name: install python
          uses: actions/setup-python@v3
          with:
            python-version: 3.11

        - name: install poetry
          run: |
            pip install poetry
            poetry config virtualenvs.create false
            cd backend/app/
            poetry install --no-root

        - name: run docker-compose
          run: |
            echo "TEST='yes'" >> example.env
            mv example.env .env
            echo "PG_PA: $(<'.env' )" 
            docker-compose up -d
            sleep 60
            docker-compose logs